// <auto-generated />
namespace DoanDinhTam_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class upadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202106060842191_upadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
